media:
  input: src/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    fields:
      - name: title
        type: string
      - name: description
        type: string
      - name: date
        type: date
      - name: image
        type: image
      - name: alt
        type: string
      - name: credit
        type: string
      - name: tags
        type: string
        list: true
      - name: body
        type: rich-text